//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssues
    {
        public int IssueID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<System.DateTime> ExpectedReturnDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> OverdueFine { get; set; }
        public string Notes { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Readers Readers { get; set; }
        public object ReturnDate { get; internal set; }
        public DateTime DueDate { get; internal set; }
        public string ISBN { get; internal set; }
    }
}
