//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReviews
    {
        public int ReviewID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> ReaderID { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public string ReviewText { get; set; }
        public Nullable<bool> IsRecommended { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Readers Readers { get; set; }
        public string ISBN { get; internal set; }
    }
}
