//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BookAuthors = new HashSet<BookAuthors>();
            this.BookIssues = new HashSet<BookIssues>();
            this.BookReviews = new HashSet<BookReviews>();
        }
    
        public int BookID { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string OriginalTitle { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public string PublishHouse { get; set; }
        public string Language { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> GenreID { get; set; }
        public string Description { get; set; }
        public byte[] CoverImage { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> TotalCopies { get; set; }
        public Nullable<int> AvailableCopies { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookAuthors> BookAuthors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookIssues> BookIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookReviews> BookReviews { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
